### ISSUE TITLE
Checklist for javascript web development

### ISSUE THREAD

**Issue by kiquenet** [mikesprague/webdev-resources#3]
It would be very interesting, checklist about web development.

About accessibility: https://dzone.com/articles/the-accessibility-checklist-i-

And very useful resources and tools:  I'm a huge fan of the dump function.

http://ajaxian.com/archives/javascript-variable-dump-in-coldfusion 
https://stackoverflow.com/questions/208016/how-to-list-the-properties-of-a-javascript-object/3937321?noredirect=1#comment77658479_3937321

Coldfusion dump for javascript not found (http://www.netgrow.com.au/assets/files/dump/dump.zip gives 404 error by redirect)

Now, in 2017 what do you use for dump javascript? console.log for Firebug FF, Chrome ?

javascript dump is better ?

Thx a lot

**Comment by mikesprague** [comment]
Thanks for the link/info! I'm going to skip adding the accessibility checklist since it's from 2008.

I personally use the console if I'm not working with a debugger as far as dumping variables etc. If you were a fan of that cfdump-like functionality for JS, this may interest you: https://j11y.io/javascript/prettyprint-for-javascript/

**Comment by kiquenet** [comment]
Other  dump function: https://github.com/ozmartian/js-cfdump


In modern browsers (IE9+, FF4+, Chrome5+, Opera12+, Safari5+) you can use the built in Object.keys method and console.log, Not pretty, but very simple.

References:
https://stackoverflow.com/questions/208016/how-to-list-the-properties-of-a-javascript-object/3937321?noredirect=1#comment77658479_3937321

https://stackoverflow.com/questions/684672/how-do-i-loop-through-or-enumerate-a-javascript-object
